### ISSUE TITLE
Digital certificate error & The string is missing

### ISSUE THREAD

**Issue by MetaspIoit** [dievus/ADGenerator#1] opened 2021-05-22 05:38 UTC
Found out that I needed to run this command on each start up to run the .ps1 files
`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`

The other issue I'm having is a strings is missing terminator: 
![29096a8ce9349b4b0721e2ff9df2c1a2](https://user-images.githubusercontent.com/56143890/119215852-a6ac1400-bb13-11eb-886c-c04ef45413f5.png)

**Comment by aspwning** [comment] 2021-05-22 06:21
Found the issue. 

Missing quotation on line 230 "PolicyStore"

**Comment by dievus** [comment] 2021-05-22 13:42
Cannot reproduce.  There is also no reason with a fresh windows server deployment to need to bypass scripting requirements.  Closing.

**Closed as completed by dievus** 2021-05-22 13:42 UTC
